# Generated by Django 3.2.8 on 2021-12-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historic_facts', '0002_historicfact_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicfact',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
